name: ChatChannels
main: me.simplicitee.ChatChannels
version: 5.1
author: Simplicitee
description: Unique and easy chat channels plugin
softdepend: [Feudal, Factions]
commands:
    channel:
        aliases: [channel, ch]
        description: Main command for chatchannels
        permission: chatchannels.command.channel
        default: true
        permission-message: You do not have permission to do that!