name: ChatChannels
main: me.simplicitee.ChatChannels
version: 1.6.0
author: Simplicitee
description: Unique and easy chat channels plugin
commands:
    channel:
        aliases: [channel, ch, chatchannel, chatchannels, channels, chatch, chat, cc]
        description: Main command for chatchannels
        permission: chatchannels.command.channel
        default: true
        permission-message: You do not have permission to do that!